[project]
name = "secure-data-encryption-system-using-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "cryptography>=44.0.2",
    "standard>=1.0.3",
    "streamlit>=1.44.1",
]
